// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AwsarchitectureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void awsarchitecture() {
    driver.get("https://aws.amazon.com/");
    driver.manage().window().setSize(new Dimension(1494, 886));
    js.executeScript("window.scrollTo(0,1168.6666259765625)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Architecture Center")).click();
    vars.put("win3787", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3787").toString());
    driver.findElement(By.cssSelector(".lb-xbcol:nth-child(1) .lb-none-pad .lb-txt-bold")).click();
    driver.findElement(By.cssSelector(".lb-grid:nth-child(4)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("AWS Well-Architected Framework")).click();
    vars.put("win6166", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6166").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".lb-none-v-margin:nth-child(1) > p > b"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Serverless Applications Lens – AWS Well-Architected")).click();
    vars.put("win759", waitForWindow(2000));
    driver.switchTo().window(vars.get("win759").toString());
    driver.findElement(By.linkText("Definitions")).click();
    driver.findElement(By.linkText("Compute layer")).click();
    driver.findElement(By.linkText("Data layer")).click();
    driver.findElement(By.linkText("Edge layer")).click();
    driver.findElement(By.cssSelector("#\\36-1661867118400-9736 .awsui_list-item_l0dv0_4zxmg_155:nth-child(6)")).click();
    driver.findElement(By.linkText("Scenarios")).click();
    driver.findElement(By.linkText("RESTful microservices")).click();
    driver.findElement(By.linkText("Alexa skills")).click();
    driver.findElement(By.linkText("Mobile backend")).click();
    driver.findElement(By.linkText("Event-driven architectures")).click();
    driver.findElement(By.linkText("Conclusion")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("AWS glossary")).click();
  }
}
