// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AwsblogTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void awsblog() {
    driver.get("https://aws.amazon.com/");
    driver.manage().window().setSize(new Dimension(1494, 886));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Blogs")).click();
    vars.put("win6162", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6162").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".m-card:nth-child(2) b")).click();
    vars.put("win854", waitForWindow(2000));
    driver.switchTo().window(vars.get("win854").toString());
    js.executeScript("window.scrollTo(0,300)");
    driver.findElement(By.linkText("Blog Home")).click();
    driver.findElement(By.id("awsf-filtered-posts-category-big-data")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".m-card:nth-child(4) b")).click();
    vars.put("win5377", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5377").toString());
    js.executeScript("window.scrollTo(0,1200)");
  }
}
